feat: Manage-SDK, removeForApp, clear and clearForApp for secure storage
rdkcentral/firebolt-apis pull request #127
Opened 2023-05-22 15:42 UTC by kevinshahfws

2023-06-01 21:18 UTC, jlacivita requested changes

2023-06-01 21:18 UTC, jlacivita commented on src/openrpc/secure_storage.json
> +      "summary": "Set or update a secure data value from distributor for an appId",
It's not necessary going to be called by a distributor. Maybe change this to "for a specific app."

2023-06-01 21:18 UTC, jlacivita commented on src/openrpc/secure_storage.json
> +      "summary": "Remove all secure data values by distributor for an appId",
Same not on "distributor"

2023-06-01 21:18 UTC, jlacivita commented on src/openrpc/secure_storage.json
> +      "name": "removeAll",
we should call this `removeAllForApp` and have a second method called `removeAll` that doesn't include the `appId` parameter and `uses` the capability.

I also think `clear` might be a better name, but that's subjective.

2023-06-02 21:31 UTC, kpears201 commented on src/openrpc/secure_storage.json
> +            "xrn:firebolt:capability:storage:secure"
I do think changing the capability of a method is a breaking change. If we change this for 0.13, then the `storage:secure` capability will technically no longer exist. Not sure what that really means for apps using 0.12 with Ripple that supports 0.13. I guess we would have to map permissions to a capability that no longer exists?

>I'm not sure storage:secure is a good name, as it implies we might have insecure storage, too.
The whole module is called SecureStorage, so shouldn't that statement apply to the module name?
The name SecureStorage is already pretty widely used, might be too late.

2023-06-02 21:43 UTC, jlacivita commented on src/openrpc/secure_storage.json
> +            "xrn:firebolt:capability:storage:secure"
ok i’m sold

2023-06-07 14:00 UTC, jlacivita commented on src/openrpc/secure_storage.json
> +        }
key should be required, right? we don't want people using this api to clear all of the keys in app/scope, that's what clear is for.

2023-06-07 18:11 UTC, jlacivita approved these changes
Looks good, thanks!

2023-06-07 18:20 UTC, merged

2023-06-09 13:49 UTC, jlacivita commented
:tada: This PR is included in version 0.13.0-next.1 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-apis/releases/tag/v0.13.0-next.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-12 16:06 UTC, jlacivita commented
:tada: This PR is included in version 0.13.0 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-apis/releases/tag/v0.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: