First pass at requirements
rdkcentral/firebolt-apis pull request #141
Opened 2023-06-22 17:34 UTC by jlacivita

2024-04-24 14:12 UTC, satlead commented on requirements/specifications/media/media-pipeline.md
> +The audioSettings **MUST** include an `audioLoundnessEquivalence` boolean property.
typo audioLoudnessEquivalence

2024-05-23 19:47 UTC, alkalinecoffee commented
To merge into #141 

Adds some new methods per the requirements doc.

The highlights are:

- For consistency, resolution now always refers to a resolution defined in pixels as width/height (e.g. `[1920, 1080]`)
- For consistency, video mode now always refers to the shorthand resolution and optional frame rate (e.g. `1080p60`)

## Newly added methods

### AudioOutput

- `mode`: Return the audio output mode currently supported by the platform, e.g. `stereo`

### Device

- `audioFormatSupported`: Check whether content of a given audio format is supported by the device's current configuration, e.g. `bool`
- `hdcpVersion`: Get the latest HDCP version supported by the device, e.g. `2.2`
- `hdrProfile`: Returns the current HDR profile set on the device, e.g. `hdr10`
- `hdrProfiles`: Returns all HDR profiles supported by the device, e.g. `[hdr10, hdr10plus, hlg]`
- `sourceFrameRateUsed`: Check whether the HDMI output frame rate is set to follow the video source frame rate.
- `videoFormatSupported`: Whether video content of the given format is supported by the device's current configuration, returns `bool`
- `videoMode`: Returns the current video output mode of the device, e.g. `1080p60`
- `videoModes`: Returns an array of all valid video output modes that the device supports, regardless of any connected display, e.g. `[1080p50, 1080p60]`.

### Display

- `size`: Get the width and height of the display panel (in centimeters), e.g. `[157, 91]`
- `colorDepth`: Get the supported color depth of the display panel in bits, e.g. `10`
- `hdrProfiles`: Returns all HDR profiles supported by the display, e.g. `[hdr10, hdr10plus, hlg]`
- `refreshRate`: Get the native refresh rate of the display device (in Hz), e.g. `60`
- `resolution`: Get the resolution of the display device in pixels, e.g. `[1920, 1080]`
- `resolutionName`: Get a user-friendly resolution name of the display device, e.g. `uhd`

### Media Info

- `activeAudioFormats`: Get a list of the active audio formats currently used across all media pipelines, returns an array of  `MediaInfo.AudioFormat` objects
- `activeVideoFormats`: Get a list of the active video formats currently used across all media pipelines, returns an array of  `MediaInfo.VideoFormat` objects
- `audioFormat`: Get the audio format currently used by the specified media pipeline, returns `MediaInfo.AudioFormat`
- `onActiveAudioFormatsChanged`: Get notified when the active audio formats used across all media pipelines starts, stops, or changes, returns an array of  `MediaInfo.AudioFormat` objects
- `onActiveVideoFormatsChanged`: Get notified when the active video formats used across all media pipelines starts, stops, or changes, returns an array of `MediaInfo.VideoFormat` objects
- `videoFormat`: Get the video format currently used by the specified media pipeline, returns `MediaInfo.VideoFormat`

### Deprecated Methods

- `Device.hdcp`: Get the supported HDCP versions available for content transmission.  Team decided to deprecate boolean map methods. Superceded by `Device.hdcpVersion`
- `Device.hdr`: Returns an array of valid HDR profiles that the device supports. Team decided to deprecate `booleanMap` methods. Superceded by `Device.hdrProfiles`
- `Device.screenResolution`: Removed in favor of the more descriptive `Device.videoResolution` or `Display.resolution`

### Notes

- Some methods (such as `Device.hdrProfiles` and `Display.hdrProfiles`) are domain-specific, in that they only return values for the device or display respectively, putting the onus on the developer to determine what content works on the customer's equipment
  - Should we consider new methods to evaluate capabilities of the user's entire AV chain / system?  This might include the device, display, AV receiver, physical connections, etc
  - Note that`Device.videoModes` is one such method that is currently specced to consider capabilities of both the device and display
- How are errors expected to be handled?  For instance, if a `Display` method is called but no display is present, should the method return successfully with a null-ish value, or should the SDK return an error?

2024-07-03 20:22 UTC, kevinshahfws requested changes

2024-07-03 20:22 UTC, kevinshahfws commented on src/openrpc/media_info.json
> +            "name": "onActiveAudioFormatsChanged",
We don't need this method explicitly defined because activeAudioFormats has been tagged with _**property**_

2024-07-03 20:22 UTC, kevinshahfws commented on src/openrpc/media_info.json
> +            "name": "onActiveVideoFormatsChanged",
We don't need this method explicitly defined because activeVidioFormats has been tagged with _**property**_

2024-07-08 13:29 UTC, kevinshahfws commented on src/openrpc/device.json
> +      "name": "onVideoOutputChanged",
I don't see any Getter for videoOutput... Should we have it?

2024-07-08 13:29 UTC, kevinshahfws commented on src/openrpc/device.json
> +      "name": "onAudioOutputChanged",
I don't see any Getter for audioOutput... Should we have it?

2024-07-16 12:43 UTC, alkalinecoffee commented
Adds some new methods per the requirements doc.

The highlights are:

- For consistency, resolution now always refers to a resolution defined in pixels as width/height (e.g. `[1920, 1080]`)
- For consistency, video mode now always refers to the shorthand resolution and optional frame rate (e.g. `1080p60`)

## Newly added methods/events

### Device

- `audioMode`: Get the current audio output mode of the device, e.g. `stereo`
- `audioModes`: Get all audio output mode supported by the device, e.g. `[stereo, surround]`
- `maxHdcpVersion`: Get the latest/maximum HDCP version supported by the device, e.g. `2.2`
- `colorDepth`: Returns the current color depth set on the device, e.g. `10`
- `maxColorDepth`: Returns the maximum supported color depth on the device, e.g. `10`
- `colorSpace`: Returns the current color space set on the device, e.g. `"YCbCr422"`
- `hdrProfile`: Returns the current HDR profile set on the device, e.g. `hdr10`
- `hdrProfiles`: Returns all HDR profiles supported by the device, e.g. `[hdr10, hdr10plus, hlg]`
- `quantizationRange`: Returns the current quantization range set on the device, e.g. `limited`
- `sourceFrameRateUsed`: Check whether the HDMI output frame rate is set to follow the video source frame rate.

- `videoMode`: Returns the current video output mode of the device, e.g. `1080p60`
- `videoModes`: Returns an array of all valid video output modes that the device supports, regardless of any connected display, e.g. `[1080p50, 1080p60]`.
- `videoResolution`: Returns the current video output resolution of the device, e.g. `{width: 1920, height: 1080}`
- `onPreVideoModeChanged": Get notified before the video mode/resolution is changed

### Display

- `colorDepth`: Get the supported color depth of the display panel in bits, e.g. `10`
- `colorimetry`: Get all colorimetry values from the display panel, e.g. `[BT2020RGB, BT2020YCC]`
- `hdrProfiles`: Returns all HDR profiles supported by the display, e.g. `[hdr10, hdr10plus, hlg]`
- `manufacturer`: Get the manufacturer of the display device, e.g. `Samsung Electric Company`
- `productName`: Get the product name/model of the display device, e.g. `Q80A`
- `refreshRate`: Get the native refresh rate of the display device (in Hz), e.g. `60`
- `resolution`: Get the resolution of the display device in pixels, e.g. `[1920, 1080]`
- `resolutionName`: Get a user-friendly resolution name of the display device, e.g. `uhd`
- `size`: Get the width and height of the display panel (in centimeters), e.g. `[157, 91]`
- `sourcePhysicalAddress`: Get the source physical address of the display device, e.g. .`3.0.0.0`

### Media Info

- `activeAudioFormats`: Get a list of the active audio formats currently used across all media pipelines, returns an array of  `MediaInfo.AudioFormat` objects
- `activeVideoFormats`: Get a list of the active video formats currently used across all media pipelines, returns an array of  `MediaInfo.VideoFormat` objects
- `audioFormat`: Get the audio format currently used by the specified media pipeline, returns `MediaInfo.AudioFormat`
- `onActiveAudioFormatsChanged`: Get notified when the active audio formats used across all media pipelines starts, stops, or changes, returns an array of  `MediaInfo.AudioFormat` objects
- `onActiveVideoFormatsChanged`: Get notified when the active video formats used across all media pipelines starts, stops, or changes, returns an array of `MediaInfo.VideoFormat` objects
- `videoFormat`: Get the video format currently used by the specified media pipeline, returns `MediaInfo.VideoFormat`

### AV System

- `audioFormatSupported`: Check whether content of a given audio format is supported by the device's current configuration, returns `bool`
- `videoFormatSupported`: Whether video content of the given format is supported by the device's current configuration, returns `bool`

### Deprecated Methods

- `Device.hdcp`: Get the supported HDCP versions available for content transmission.  Team decided to deprecate `booleanMap` methods. Superceded by `Device.hdcpVersion`
- `Device.hdr`: Returns an array of valid HDR profiles that the device supports. Team decided to deprecate `booleanMap` methods. Superceded by `Device.hdrProfiles`
- `Device.screenResolution`: Removed in favor of the more descriptive `Device.videoResolution` or `Display.resolution`

2025-12-19 10:08 UTC, closed without merging