feat: Included entity array in Search Intent
rdkcentral/firebolt-apis pull request #304
Opened 2024-08-22 21:15 UTC by kevinshahfws

2024-08-23 15:24 UTC, jlacivita requested changes

2024-08-23 15:31 UTC, kpears201 commented on src/schemas/intents.json
> +                                                        "$ref": "https://meta.comcast.com/firebolt/entity#/definitions/MovieEntity"
You can use `ProgramEntity` which is an already defined list of these entities.
But how come searching can only suggest programs? Seems like Channels and Music makes sense to suggest too?

2024-08-23 16:19 UTC, jlacivita approved these changes, later dismissed
Looks good

2024-08-23 16:19 UTC, jlacivita commented on src/openrpc/discovery.json
> +                  "query": "a cool show",
I guess we should maybe search for "a cool movie" given the results...

2024-08-23 16:19 UTC, jlacivita commented on src/openrpc/discovery.json
> +                  "query": "a cool show",
sorry, I know I sent you that example :)

2024-08-23 16:21 UTC, kpears201 approved these changes, later dismissed

2024-08-23 17:58 UTC, jlacivita approved these changes, later dismissed

2024-09-03 13:45 UTC, jlacivita submitted a review, later dismissed

2024-09-03 16:40 UTC, jlacivita approved these changes

2024-09-03 16:49 UTC, merged

2024-09-03 16:53 UTC, kschrief commented
:tada: This PR is included in version 1.4.0-next.1 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-apis/releases/tag/v1.4.0-next.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-09-23 20:41 UTC, kschrief commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-apis/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: