CI Pipeline to build and test CPP SDK core module
rdkcentral/firebolt-apis pull request #334
Opened 2024-10-08 14:34 UTC by AdityaKasar

2024-10-08 15:15 UTC, kschrief requested changes

2024-10-08 15:15 UTC, kschrief commented on .github/workflows/cxx-build.yml
> +  push:
We would want these running on PRs, not pushes.

2024-10-08 15:15 UTC, kschrief commented on .github/workflows/utils.sh
> +  cat ./build.sh
Why are we "cat"ing this file and others below?

2024-10-08 15:15 UTC, kschrief commented on .github/workflows/utils.sh
> +function buildCoreCPPSDK() {
Can we combine the 3 build functions into one function that takes in an SDK parameter? We'll have other SDKs to worry about down the road and it'll be easier to add it as a parameter.

2024-10-08 15:15 UTC, kschrief commented on .github/workflows/cxx-build.yml
> +      - name: Build SDK
It looks like we're only building core here? Can we also build the other SDKs?

2024-10-08 15:15 UTC, kschrief commented on .github/workflows/utils.sh
> +function buildCoreCPPSDK() {
I also don't see these functions being used anywhere.

2024-10-11 12:17 UTC, AdityaKasar commented
Requesting a re-review 

- Addressed previous comments 
- Implemented caching mechanism for faster installation of npm dependencies 
- Pre-compiling Thunder and openrpc artifacts and used artifacts uploading feature 
- Building 3 SDKs parallelly 

This is the final pipeline for reference: https://github.com/rdkcentral/firebolt-apis/actions/runs/11291931107

2024-10-15 21:14 UTC, AdityaKasar commented
latest pipeline run: https://github.com/rdkcentral/firebolt-apis/actions/runs/11354300763/job/31581481906

2024-10-16 17:28 UTC, kschrief approved these changes

2024-10-16 18:41 UTC, kschrief approved these changes

2024-10-16 18:42 UTC, merged

2024-10-16 18:46 UTC, kschrief commented
:tada: This PR is included in version 1.5.0-next.2 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-apis/releases/tag/v1.5.0-next.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-03-03 20:10 UTC, kschrief commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-apis/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-07-29 11:21 UTC, kschrief commented
:tada: This PR is included in version 1.5.0-next-major.1 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-apis/releases/tag/v1.5.0-next-major.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: